# tinted-foot
# Scheme name: nosferatu
# Scheme author: morgan
# Template author: Tinted Theming (https://github.com/tinted-theming)

[colors]
foreground=f8f8f2
background=282a36
regular0=363447 # black
regular1=ff5555 # red
regular2=50fa7b # green
regular3=f1fa8c # yellow
regular4=bd93f9 # blue
regular5=ff79c6 # magenta
regular6=8be9fd # cyan
regular7=f8f8f2 # white
bright0=44475a # bright black
bright1=ff5555 # bright red
bright2=50fa7b # bright green
bright3=f1fa8c # bright yellow
bright4=bd93f9 # bright blue
bright5=ff79c6 # bright magenta
bright6=8be9fd # bright cyan
bright7=ffffff # bright white
16=ffb86c
17=ffb86c
18=363447
19=44475a
20=9ea8c7
21=f8f8f2
